### ISSUE TITLE
What is a client, and what is a server?

### ISSUE THREAD

**Issue by alexanderedge** [guardian/apps-rendering#172]
Would it be possible to add to the readme what _client_ and _server_ mean in the context of apps-rendering? Why do we need both? One might consider the app to be a client, so how does the app fit in?

**Comment by alexduf** [comment]
That's a good point, I guess we should rename them to Native and Webview

**Comment by JamieB-gu** [comment]
Which references to *client* and *server* are you referring to?

**Comment by webb04** [comment]
Yeah there is apps-rendering code that will run on:
- Node server
- webView client

**Comment by JamieB-gu** [comment]
In general, in this codebase, whenever the term `client` is used unqualified it means client-side JavaScript running in a web browser, and `server` unqualified means server-side JavaScript code running on our Node server.

I think anything relating to the Native-WebView comms framework should be at minimum qualified with terms like `native` and `webview`, as @alexduf mentioned.

As an aside, probably everything relating to the _MAPI_ server should be qualified with the term `mapi` if possible, to avoid any confusion there.

**Comment by JamieB-gu** [comment]
> One might consider the app to be a client

I think in the context of MAPI the app *is* a client.

However, in the context of apps-rendering, the only time any interaction happens with the app directly is in the native-webview comms layer, which I guess you could call a two-way/peer-to-peer communication.
